version: 2.1

jobs:
  build:
    docker:
      - image: "node:17"
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: lint
          command: npm run lint
      - run:
          name: format
          command: npm run format:check
      - run:
          name: test
          command: npm test -- --ensure
